### ISSUE TITLE
hi pls help

### ISSUE THREAD

**Issue by komino4** [Mengeroshi/Bitcoin-Seed#1]
C:\np>node addrs.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\np\addrs.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by komino4** [comment]
ahh oké 

node addr.js
